### PR TITLE
适配Wechaty1.x 字段

### PR DESCRIPTION
**Pull request by leochen-g**
1、适配Wechaty 1.x 部分字段
2、修复message为空的问题
3、解决头像为空的问题

### CODE REVIEW

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for the improvements!

**Comment by leochen-g** [comment]
> LGTM
> 
> Thank you very much for the improvements!

跑单元测试的 测试公众号好像是不通的，导致没法通过test

**Comment by huan** [comment]
```
Error: OfficialAccount sendCustomMessage() can send message <{"content":"wechaty-puppet-official-account CI testing","msgtype":"text","touser":"ooEEu1Pdb4otFUedqOx_LP1p8sSQ"}>
```

The OA account in unit tests is my developing account; it can only be successful if the target user sends a message to the OA account in the past 24 hours because of the limitation of Tencent.

I (my WeChat account in this OA is `ooEEu1Pdb4otFUedqOx_LP1p8sSQ`) have just sent a message to the OA account in the unit test; I think it will work in the following 24 hours.

Please feel free to provide better solutions if you have any new ideas, and I'm open to discussing them.

Thanks!

**Comment by huan** [comment]
It seems the CI works:

image

**Pull request merged**
